// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bCbvUcteWZd6HDy751hPeA
// Component: TpTCcCVK2I7ezu
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: lTr2G1MxBk6FF/component
import Button from "../../Button"; // plasmic-import: i2RFTUsbFArGA/component
import Footer from "../../Footer"; // plasmic-import: 1PBy2w-ZdBEOO/component

import { useScreenVariants as useScreenVariantsfD2Y32Q3IrH } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: fD2Y32q_3-ir_h/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: bCbvUcteWZd6HDy751hPeA/projectcss
import sty from "./PlasmicBlog.module.css"; // plasmic-import: TpTCcCVK2I7ezu/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ftfnPPuGWa6LBB/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: FiRrK1dnK-Uz7E/icon
import neonbrand3GznpblImWcUnsplashjpgIy0DQz8FmvpTaj from "./images/neonbrand3GznpblImWcUnsplashjpg.jpeg"; // plasmic-import: IY0dQZ8fmvpTAJ/picture
import istockphoto1306171737170667Ajpg2WmrsHZqQhCfz8I from "./images/istockphoto1306171737170667Ajpg2.jpeg"; // plasmic-import: WmrsHZqQHCfz8I/picture
import fakurianDesignPPTwRTkvXqUnsplashjpgGS4S3WvRjpDw0Y from "./images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg"; // plasmic-import: gS4s3wvRJPDw0Y/picture
import fakurianDesignLfbhDph3QYUnsplashjpgLvN7Aae6Ya5Fja from "./images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg"; // plasmic-import: LvN7aae6Ya5fja/picture
import xpsOcAuPlfZxEcUnsplashjpgUvedXiNcw4SuUg from "./images/xpsOcAuPlfZxEcUnsplashjpg.jpeg"; // plasmic-import: UvedXINcw4suUG/picture
import corinneKutzTMi2R5NfoUnsplashjpg621Utzw3MzFOy from "./images/corinneKutzTMi2R5NfoUnsplashjpg.jpeg"; // plasmic-import: 621utzw3MzF-OY/picture
import stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgVqLeZso19XwMTt from "./images/stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpg.jpeg"; // plasmic-import: vqLEZso19xwMTt/picture

export type PlasmicBlog__VariantMembers = {};

export type PlasmicBlog__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog__VariantsArgs;
export const PlasmicBlog__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog__ArgsType = {};
type ArgPropType = keyof PlasmicBlog__ArgsType;
export const PlasmicBlog__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  pageBanner?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultBlogProps {
  className?: string;
}

export const defaultBlog__Args: Partial<PlasmicBlog__ArgsType> = {};

function PlasmicBlog__RenderFunc(props: {
  variants: PlasmicBlog__VariantsArgs;
  args: PlasmicBlog__ArgsType;
  overrides: PlasmicBlog__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultBlog__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsfD2Y32Q3IrH()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox___7Qb5O)}>
            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___3Kahs)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__nbkKs)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__zxgtB)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__rg5Ix)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Blog"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pXlSp
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                        }
                      </div>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__rQtp5)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rwWlj)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("100%" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("lazy" as const)
                          : ("lazy" as const)
                      }
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: neonbrand3GznpblImWcUnsplashjpgIy0DQz8FmvpTaj,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                          : {
                              src: neonbrand3GznpblImWcUnsplashjpgIy0DQz8FmvpTaj,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                      }
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__x8V0D)}>
              <div className={classNames(projectcss.all, sty.freeBox__ew1Pe)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__qhgdO)}
                >
                  <div className={classNames(projectcss.all, sty.column__reVy)}>
                    <div
                      className={classNames(projectcss.all, sty.columns__j1YCf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ibWlA
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__eAsb)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: istockphoto1306171737170667Ajpg2WmrsHZqQhCfz8I,
                            fullWidth: 509,
                            fullHeight: 340,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__zwnd)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xxBt3
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4___0Dpwt
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__el2Rc
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__fM1Z0
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wfp4T
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Read post"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__iCcO2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__bhud9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__b1MeK
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___6D6ZD)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: fakurianDesignPPTwRTkvXqUnsplashjpgGS4S3WvRjpDw0Y,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__qP5Xb
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__k119O
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__jBj3H
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oD6Xl
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__ltwRr
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ic8Zr
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__kevbu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__fjy3X)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__vJyN1
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__nwmhs)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: fakurianDesignLfbhDph3QYUnsplashjpgLvN7Aae6Ya5Fja,
                            fullWidth: 1920,
                            fullHeight: 1080,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___8JNjW
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yPgjd
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__jQqyn
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cwx3Y
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__oD2Mf
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__vpgcv
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___4UA2V)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__e8Iw7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4TjG
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__sNwex)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: xpsOcAuPlfZxEcUnsplashjpgUvedXiNcw4SuUg,
                            fullWidth: 640,
                            fullHeight: 360,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3ZmRv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j6V
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__bkg6M
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__v2UcG
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__jrulF
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__imLqe
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___14W05)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__hpCld)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__vckAf
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ipLfp)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: corinneKutzTMi2R5NfoUnsplashjpg621Utzw3MzFOy,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__yo6Wi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2F0Dp
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__nmj18
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nILk
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__rf1Pc
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__vy02H
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___2SOcT)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__zpqQl)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fWKgR
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ehk9)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgVqLeZso19XwMTt,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uCz0S
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__g280
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4___7DNgg
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qqp21
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__nqpAv
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__zSdxU
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__yFnSl)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__kJzxk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mufto
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__q600G)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: neonbrand3GznpblImWcUnsplashjpgIy0DQz8FmvpTaj,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__zieVs
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rKGv3
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__vgjNd
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__neeSm
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__qgoHa
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hfXia
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__zmDuG)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__kUfV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uz8Sd
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__famVz)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"100%" as const}
                          loading={"lazy" as const}
                          src={{
                            src: neonbrand3GznpblImWcUnsplashjpgIy0DQz8FmvpTaj,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__tBdC)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lPjsy
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__wWo1A
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3FJnw
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__woSv
                            )}
                            color={"blue" as const}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__sntvG
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanner", "h1", "footer"],
  header: ["header"],
  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  pageBanner: "div";
  h1: "h1";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog__VariantsArgs;
    args?: PlasmicBlog__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlog__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBlog__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlog__ArgProps,
      internalVariantPropNames: PlasmicBlog__VariantProps
    });

    return PlasmicBlog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog";
  } else {
    func.displayName = `PlasmicBlog.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog = Object.assign(
  // Top-level PlasmicBlog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicBlog
    internalVariantProps: PlasmicBlog__VariantProps,
    internalArgProps: PlasmicBlog__ArgProps
  }
);

export default PlasmicBlog;
/* prettier-ignore-end */
